#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2017 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "gruvbox"
    colorscheme_bg = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "arrow"
    statusline_inactive_separator = "arrow"
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_statusline_mode = false
    # 使用原生快捷键
    #vimcompatible = true
    # 文件树在左侧
    filetree_direction="left"

    #编辑器启动前的一些配置载入
    bootstrap_before = "xbbconfig#before"
    bootstrap_after = "xbbconfig#after"

    default_indent = 4
    windows_smartclose=''
    disabled_plugins = ["neomake.vim"]

#    enable_ycm = true

[[layers]]
name = 'colorscheme'

# Enable autocomplete layer
[[layers]]
name = 'autocomplete'
auto-completion-return-key-behavior = "complete"
auto-completion-tab-key-behavior = "smart"

[[layers]]
name = 'shell'
default_position = 'top'
default_height = 30

[[layers]]
name = 'tools'

[[layers]]
name = 'unite'

[[layers]]
  name = "checkers"
  show_cursor_error = false

[[layers]]
name = "lang#c"
enable_clang_syntax_highlight = false
clang_executable = "D:/Program Files/LLVM/bin"
libclang_path = "D:/Program Files/LLVM/bin"
  [layer.clang_std]
    c = "c11"
    cpp = "c++1z"
    objc = "c11"
    objcpp = "c++1z"

[[layers]]
name = "lang#csharp"

[[custom_plugins]]
name = "vimwiki/vimwiki"
#on_cmd=["VimwikiUISelect", "VimwikiIndex", "VimwikiDiaryIndex", "VimwikiMakeDiaryNote"]
merged = 0

# 对其插件
[[custom_plugins]]
name="junegunn/vim-easy-align"
merged = 0

[[layers]]
  name = "lang#markdown"

# python 语言设置
[[layers]]
  name = "lang#python"
  format-on-save = 1

#[[layers]]
#  name = "tags"
